---
title: "PSV Analysis"
author: DIME and PSV Safety Awards
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
    toc_fold: TRUE
    highlight: tango
    keep_md: yes
    theme: cosmo
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r dataprep, echo=FALSE, include=FALSE}
# Setup ------------------------------------------------------------------------
if(Sys.info()[["user"]] == "robmarty") github <- "~/Documents/Github/PSV-Rider-Feedback/"

source(file.path(github, "_psv_feedback_master.R"))

# Load Data --------------------------------------------------------------------
data <- readRDS(file.path(dropbox_dir, "Data", "Rider Feedback", 
                          "All Data", "FinalData", "rider_feedback.Rds"))

```

# Overall Responses

## Daily - By Posted Award Type
```{r, fig.height=16}

# data_award <- data %>%
#   filter(!is.na(complete_date)) %>%
#   group_by(date, award_type, month) %>%
#   dplyr::summarise(N = n()) 
# 
# data_total <- data %>%
#   filter(!is.na(complete_date)) %>%
#   group_by(date, month) %>%
#   dplyr::summarise(N_total = n()) %>%
#   ungroup() 
# 
# ggplot() +
#   geom_col(data = data_award, 
#            aes(x=date, y=N,
#                fill = award_type,
#                group = award_type)) +
#   geom_text(data = data_total,
#             aes(x=date, y=N_total,
#                 label = N_total), 
#             color = "black", 
#             fontface = "bold",
#             size=3) +
#   #geom_vline(xintercept = as.Date(PILOT_2_DATE),
#   #           color = "red") +
#   labs(fill = "Award",
#        x = "") +
#   theme_minimal() +
#   facet_wrap(~month,
#              ncol = 1,
#              scales ="free") +
#   theme(strip.text = element_text(face = "bold", size=16, color = "black", hjust = 0.5))
```

